version: "3"
services:
  hyperscale-application-showcase:
    image: "hyperscale-application-showcase:latest"
    scale: 3
    ports: 
    - "3001-3003:3000"
    restart: always
    volumes:
    - "./hosts.conf:/etc/hosts:rw"
    environment:
      REDIS_URL: redis

  redis-1:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      redis-network:
        ipv4_address: 172.18.0.2
  redis-2:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6379"
    networks:
      redis-network:
        ipv4_address: 172.18.0.3
  redis-3:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6381:6379"
    networks:
      redis-network:
        ipv4_address: 172.18.0.4

networks:
  redis-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16