version: "3"
services:
  hyperscale-application-showcase:
    image: "hyperscale-application-showcase:live"
    scale: 6
    ports: 
    - "3000-3006:3000"
    restart: always
    volumes:
    - ".:/usr/src/app:rw"
    - "./hosts.conf:/etc/hosts:rw"
    environment:
      REDIS_URL: redis