version: "3"
proxy:
  image: "proxy-has:latest"
  scale: 1
  ports: 
  - "443:443/tcp"
  - "443:443/udp"
  - "80:80/tcp"
  - "80:80/udp"
  restart: always
  volumes:
  - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw"
  - "./selfsign-ssl/:/etc/nginx/certs/:rw"